use_frameworks!

platform :ios, '8.0'

target 'MainThreadLockChecker_Example' do
  pod 'MainThreadLockChecker', :path => '../'

  target 'MainThreadLockChecker_Tests' do
    inherit! :search_paths

    
  end
end
